// components/Layout.tsx
"use client"
import type { Metadata } from "next";
import {Capriola} from "next/font/google";
import "./globals.css";
import { useState } from "react";
import Link from "next/link";
import Sidebar from "@/components/Sidebar";
const geistSans = Capriola({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-capriola",
});
const geistMono = Capriola({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-capriola",
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const backgroundImageStyle = {
  backgroundImage: `url(
    https://st2.depositphotos.com/10956332/42514/i/450/depositphotos_425144442-stock-photo-volumetric-abstract-background-copy-space.jpg)`,
  backgroundSize: 'cover',
  backgroundPosition: 'center',
  height: '100vh',
  color: 'white',
  marginTop: 5,
  padding: 50,
  margin:10,
  alignItems: 'center',
};
const RootLayout = ({ children }: { children: React.ReactNode }) =>{
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen);
  };

  return (
    <html lang="en">
      <body
        style={backgroundImageStyle} className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="grid grid-cols-2 lg:mr-20 sm:mr-12">
      <h1 className="text-3xl float-left">M@@EYDAH</h1>
      <div className="lg:hidden">
      <button
      className="float-right text-white text-2xl focus:outline-none"
      onClick={toggleMenu}
      >
      ☰
      </button>
      {isMenuOpen && (
          <div className="mt-10 flex flex-col space-y-2  border-2 border-white  top-full left-0 w-full rounded-md mr-5">
            <Link href="/" className="text-white hover:text-gray-300 p-4">
              Home
            </Link>
            <Link href="/about" className="hover:text-gray-300 text-white p-4">
              About
            </Link>
            <Link href="/services" className="hover:text-gray-300 text-white p-4">
              Services
            </Link>
            <Link href="/contact" className="hover:text-gray-300 text-white p-4">
              Contact
            </Link>
          </div>
        )}
      </div>
      </div>
      <div className="grid lg:grid-cols-[1fr_2fr] sm:grid-cols-1 sm:grid-rows-1fr-1fr gap-4 mr-16 mt-4">
        <div className="bg-red-300">
           <Sidebar/>
        </div>
        <div className="bg-yellow-700 overflow-y-auto">
          <div className="">
            <div className="bg-fuchsia-500 flex">
                <div className="bg-slate-300 w-1/5">ccc</div>
                <div className="bg-red-700 w-4/5 sm:hidden lg:block !hidden lg:!block">
                <nav className="flex space-x-4">
                <Link href="/" className="hover:text-gray-600">
                  Home
                </Link>
                <Link href="/about" className="hover:text-gray-600">
                  About
                </Link>
                <Link href="/services" className="hover:text-gray-600">
                  Services
                </Link>
                <Link href="/contact" className="hover:text-gray-600">
                  Contact
                </Link>
              </nav>

                </div>
            </div>
            </div>
            <div className="bg-indigo-500">
              {children}
            </div>
        </div>
      </div>
      </body>
    </html>
  );
}
export default RootLayout;
