// components/Layout.tsx
"use client"
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { useState } from "react";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const backgroundImageStyle = {
  backgroundImage: `url(
    https://st2.depositphotos.com/10956332/42514/i/450/depositphotos_425144442-stock-photo-volumetric-abstract-background-copy-space.jpg)`,
  backgroundSize: 'cover',
  backgroundPosition: 'center',
  height: '100vh',
  color: 'white',
  marginTop: 5,
  padding: 50,
  margin:10,
  alignItems: 'center',
};
const RootLayout = ({ children }: { children: React.ReactNode }) =>{
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen);
  };

  return (
    <html lang="en">
      <body
        style={backgroundImageStyle} className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="grid grid-cols-2">
      <h1 className="text-3xl float-left">M@EYDAH</h1>
      <div className="lg:hidden">
      <button
      className="float-right text-white text-2xl focus:outline-none"
      onClick={toggleMenu}
      >
      ☰
      </button>
      {isMenuOpen && (
          <div className="mt-10 flex flex-col space-y-2  border-2 border-white max-w-screen-2xl rounded-md mr-5">
            <Link href="/" className="text-white hover:text-gray-300 p-4">
              Home
            </Link>
            <Link href="/about" className="hover:text-gray-300 text-white p-4">
              About
            </Link>
            <Link href="/services" className="hover:text-gray-300 text-white p-4">
              Services
            </Link>
            <Link href="/contact" className="hover:text-gray-300 text-white p-4">
              Contact
            </Link>
          </div>
        )}
      </div>
      </div>
      <div className="grid lg:grid-cols-[1fr_2fr] sm:grid-cols-1 sm:grid-rows-1fr-1fr gap-4">
        <div className="bg-red-300">
           xxx 
        </div>
        <div className="bg-yellow-700">
            vv
        </div>
      </div>
      {children}
      </body>
    </html>
  );
}
export default RootLayout;
